### PR TITLE
Win library prefix

### LINKED ISSUE #3: vtk-m package installed in non-canonical location on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Application that uses this package can't properly detect it on Windows.

AFAIU, when building and installing with `cmake`, the installation path should be set to `%LIBRARY_PREFIX%` (where packages typically reside; `%PREFIX%/Library/include` for headers and `%PREFIX%/Library/lib` for libraries) on Windows rather than `%PREFIX%` (environment configuration data).

https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html#environment-variables-set-during-the-build-process

### Installed packages

```shell
# packages in environment at D:\mambaforge\envs\raw_vtkm2:
#
# Name                    Version                   Build  Channel
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         hcc2c482_20    conda-forge
vtk-m                     2.2.0                he0c23c2_0    conda-forge
```

### Environment info

```shell
active environment : raw_vtkm2
    active env location : D:\mambaforge\envs\raw_vtkm2
            shell level : 3
       user config file : C:\Users\XXX\.condarc
 populated config files : D:\mambaforge\.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64_v4
                          __conda=24.5.0=0
                          __cuda=12.4=0
                          __win=0=0
       base environment : D:\mambaforge  (writable)
      conda av data dir : D:\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\mambaforge\pkgs
                          C:\Users\XXX\.conda\pkgs
                          C:\Users\XXX\AppData\Local\conda\conda\pkgs
       envs directories : D:\mambaforge\envs
                          C:\Users\XXX\.conda\envs
                          C:\Users\XXX\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.5.0 requests/2.32.3 CPython/3.10.14 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by JarrettSJohnson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

Fixes #3

### CODE REVIEW

**Comment by JarrettSJohnson** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
This was failing due to a gap between two different PRs that depended on each other. I've merged the second one now. In a couple hours, you can restart CI and it should pass.

**Comment by JarrettSJohnson** [comment]
Ah, thanks @h-vetinari ; I just pushed a commit similar to [this](https://github.com/conda-forge/eza-feedstock/commit/bea6208edd8fb56f6858126c53c264182e254e11)  since I saw in the Elements chatroom they had the same issue as me. Just unfortunate timing I guess. I'll revert this and will return the CI tomorrow morning.

Thanks a bunch!

**Review by vicentebolea — APPROVED** [review]
Looks good, Thanks! no need to add the description, you had a link to the issue :rocket:

**Pull request merged**
